from models.aditivo_nutritivo import AditivoNutritivo
from models.conservantes import Conservante
from models.ingredientes import Ingrediente
from models.lotes import Lote
from models.notas_fiscais import NotaFiscal
from models.picoles import Picole
from models.revendedores import Revendedor
from models.sabores import Sabor
from models.tipos_embalagem import TipoEmbalagem
from models.tipos_picole import TipoPicole